M48
; DRILL file {KiCad 7.0.11+1} date mar 07 may 2024 21:52:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-07T21:52:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.155Y-1.945
X5.155Y-5.445
X7.83Y-1.9446
X7.83Y-5.4446
T2
X7.28Y-1.9391
M30
