M48
; DRILL file {KiCad 7.0.11+1} date mié 08 may 2024 20:05:21
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-08T20:05:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.83Y-1.945
X7.83Y-5.445
T2
X1.89Y-1.895
M30
